#!/usr/bin/env python3
"""Generate PluginVersions.generated.props from PluginVersion constants in C# sources.

MSBuild imports this file so Windows file properties (File version / Product version)
match each plugin's PluginVersion string.
"""
from __future__ import annotations

import sys
from pathlib import Path

from plugin_version_sources import PROJECT_VERSION_SOURCES, read_plugin_version

ROOT = Path(__file__).resolve().parents[2]
OUT_PATH = ROOT / "PluginVersions.generated.props"


def main() -> None:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<Project>",
        "  <!-- Auto-generated by .github/scripts/generate_plugin_versions_props.py -->",
    ]

    for project_name, source in sorted(PROJECT_VERSION_SOURCES.items()):
        version = read_plugin_version(source)
        cs_path = source[0] if isinstance(source, tuple) else source
        rel = cs_path.relative_to(ROOT).as_posix()
        lines.append(f"  <!-- {rel} -->")
        lines.append(
            f'  <PropertyGroup Condition="\'$(MSBuildProjectName)\' == \'{project_name}\'">'
        )
        lines.append(f"    <Version>{version}</Version>")
        lines.append("  </PropertyGroup>")

    lines.append("</Project>")
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    try:
        main()
    except ValueError as exc:
        print(f"::error::{exc}", file=sys.stderr)
        sys.exit(1)
